name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install # or yarn install
      - name: ESLint Check
        id: eslint
        run: |
          OUTPUT=$(npx eslint . --ignore-path=.gitignore --quiet --ext=js,jsx,ts,tsx --format=json)
          echo "::set-output name=result::$OUTPUT"
      - uses: sibiraj-s/action-eslint@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
          ignore-path: .eslintignore
          ignore-pattern: |
            dist/
            lib/
      - name: Post Comment
        uses: ./.github/actions/comment-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
